### ISSUE TITLE
Import error when installing module via pip

### ISSUE THREAD

**Issue by normanius** [akaszynski/PyACVD#2]
Hi 

Just tried to run your module, but I was not able to load it.

Here is what I tried:
- `pip install PyACVD` => installed successfully
-  `python -c "import PyACVD"`

Here is what I get:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyACVD/__init__.py", line 1, in <module>
    from PyACVD import Clustering_Cython
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyACVD/Clustering_Cython.so, 2): Symbol not found: __ZTINSt8ios_base7failureE
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyACVD/Clustering_Cython.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyACVD/Clustering_Cython.so
```

I am running python 2.7.12 on MacOS 10.11.6.

**Comment by akaszynski** [comment]
I've googled __ZTINSt8ios_base7failureE and it seems that using
```
pip install -e .
```
might be something to try first.  Let me know if it works.

**Comment by normanius** [comment]
Didn't help.

**Comment by normanius** [comment]
Okay, I figured out what was the problem: Cython and ccache 

I use `ccache`, so the `CC` environment variable was set to `ccache clang -Qunused-arguments -fcolor-diagnostics`.

If I set `CC=clang`, the project compiles, installs and loads successfully, I can run the tests and generally feel pretty satisfied.

**Comment by normanius** [comment]
However, if I try other compilers, not all seem to be working:

gcc 4.6.4: `CC=gcc-4.6; CXX=g++-4.6` => **Failure**
gcc 4.9.4: `CC=gcc-4.9; CXX=g++-4.9` => **Failure**
gcc 7.2.0: `CC=gcc-7; CXX=g++-7` => **Success**

See the attached logs for the failed runs. Seems to be a problem with the architecture not being set up/supported properly.
